// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/admin" | "/admin-portal-4f28c1" | "/admin-portal-4f28c1/login" | "/cart" | "/product/[id]"
type AppRouteHandlerRoutes = "/api/admin/login" | "/api/feed" | "/api/health" | "/api/health/cloudinary" | "/api/products" | "/api/products/[id]" | "/api/sales-settings" | "/api/search-suggestions" | "/api/upload" | "/api/uploads/[...path]" | "/feed.csv"
type PageRoutes = never
type LayoutRoutes = "/" | "/admin-portal-4f28c1"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/admin": {}
  "/admin-portal-4f28c1": {}
  "/admin-portal-4f28c1/login": {}
  "/api/admin/login": {}
  "/api/feed": {}
  "/api/health": {}
  "/api/health/cloudinary": {}
  "/api/products": {}
  "/api/products/[id]": { "id": string; }
  "/api/sales-settings": {}
  "/api/search-suggestions": {}
  "/api/upload": {}
  "/api/uploads/[...path]": { "path": string[]; }
  "/cart": {}
  "/feed.csv": {}
  "/product/[id]": { "id": string; }
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/admin-portal-4f28c1": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
