export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function AdminPortalLayout({ children }: { children: React.ReactNode }) {
  // In nested layouts, don't render <html>/<body>; inherit from root layout
  return <>{children}</>;
}
